source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
gem 'json', '1.8.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
# Use Uglifier as compressor for JavaScript assets
# group :assets do
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.1.0'
  gem 'sass-rails', '>= 3.2'
  gem 'bootstrap-sass', '~> 3.3.5'
  gem 'jquery-ui-rails'
# end
gem 'simple-spreadsheet'
gem 'nokogiri'
gem 'mechanize'
# Use CoffeeScript for .coffee assets and views

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'wx_pay', '0.4.1'
gem 'swagger-docs'
gem 'rmagick',           '2.13.4'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
gem 'igetui-ruby',       '1.2.2', require: 'igetui'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'puma',              '~> 2.8.2'
gem 'resque',            '1.25.2', :require => "resque/server"
gem 'identifier',        '~> 1.1.8'
gem 'god',               '0.13.5'
gem 'redis-namespace',   '1.5.0'
gem 'redis-rails', '4.0.0'
gem 'ruby-pinyin'
gem 'redis-search'
gem 'factory_girl_rails'
gem 'pry'
# gem 'sass-rails', '~> 5.0'
gem 'will_paginate'
gem "will_paginate-bootstrap"
gem 'simple_form'
gem 'carrierwave',       '0.10.0'
gem "carrierwave-upyun"
gem 'pg', "0.18.2"
gem 'alipay', '~> 0.8.0'

# gem 'rails_autolink'
gem 'whenever', :require => false
gem 'cancancan', '~> 1.10'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
gem 'capistrano-rails', group: :development
gem 'daemons', '~> 1.2.3'
gem "font-awesome-rails"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'capistrano-bundler', '~> 1.1.2'
  gem 'capistrano-rvm',     '~> 0.1.2'
  gem 'capistrano3-puma',   '~> 0.6.1'
  gem "capistrano-resque",  "~> 0.2.1", require: false

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
