version: "2"

services:
  postgresql:
    container_name: 'homeland_postgresql'
    image: postgres:9.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    container_name: 'homeland_redis'
    image: redis:3.2.7-alpine
    mem_limit: 64m
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
  web:
    container_name: 'homeland_web'
    image: homeland/homeland:3.0.10
    links:
      - app
      - vcmix
      - worker
    env_file:
      - app.default.env
      - app.local.env
      - app.secret.env
    command: nginx -c /etc/nginx/nginx.conf
    volumes:
      - ./vcmix_backend/config/secrets.yml:/var/www/vcmix_backend/config/secrets.yml 
      - ./etc/ssl/homeland:/etc/ssl/homeland
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/html:/etc/nginx/html
      - ./etc/nginx/homeland.conf:/etc/nginx/conf.d/homeland.conf
      - ./etc/nginx/conf.d/homeland:/etc/nginx/conf.d/homeland
      - ./etc/nginx/vcmix_backend.conf:/etc/nginx/conf.d/vcmix_backend.conf
      - ./shared/ssl:/var/www/ssl
      - ./shared/cache/assets:/var/www/homeland/public/assets
      - ./data/uploads:/var/www/homeland/public/uploads
      - ./shared/cache/uploads-thumb:/var/www/cache/uploads-thumb
      - ./shared/system:/var/www/homeland/public/system
      - ./log:/var/www/log
      - ./tmp/pids:/var/www/pids
      - ./tmp/pids:/var/www/homeland/tmp/pids
      - ./shared/vcmix_backend/cache/assets:/var/www/vcmix_backend/public/assets
      - ./log/vcmix_backend:/var/www/log/vcmix_backend
      - ./log/vcmix_backend:/var/www/vcmix_backend/log
      - ./tmp/vcmix_backend:/var/www/vcmix_backend/tmp
      - ./tmp/vcmix_backend/pids:/var/www/pids
      - ./tmp/vcmix_backend/pids:/var/www/vcmix_backend/tmp/pids
    ports:
      - "80:80"
      - "443:443"
  worker:
    container_name: 'homeland_work'
    build:
      context: ./images/vcmix_backend
      dockerfile: Dockerfile
    command: bundle exec rake environment resque:work QUEUE=*
    volumes-from:
      - vcmix
    links:
      - postgresql
      - redis

  vcmix:
    container_name: 'homeland_vcmix'
    build:
      context: ./images/vcmix_backend
      dockerfile: Dockerfile
    env_file:
      - app.default.env
      - app.local.env
      - app.secret.env
    links:
      - postgresql
      - redis
    logging:
      options:
        max-size: "1g"
        max-file: "10"
    volumes:
      - ./vcmix_backend/config/database.yml:/var/www/vcmix_backend/config/database.yml
      - ./vcmix_backend/config/redis.yml:/var/www/vcmix_backend/config/redis.yml
      - ./vcmix_backend/config/secrets.yml:/var/www/vcmix_backend/config/secrets.yml
      - ./vcmix_backend/config/puma.rb:/var/www/vcmix_backend/config/puma.rb
      - ./shared/vcmix_backend/cache/assets:/var/www/vcmix_backend/public/assets
      - ./data/vcmix_backend/uploads:/var/www/vcmix_backend/public/uploads
      - ./log/vcmix_backend:/var/www/log/vcmix_backend
      - ./log/vcmix_backend:/var/www/vcmix_backend/log
      - ./tmp/vcmix_backend:/var/www/vcmix_backend/tmp
      - ./tmp/pids:/var/www/pids
      - ./tmp/vcmix_backend/pids:/var/www/pids
      - ./tmp/vcmix_backend/pids:/var/www/vcmix_backend/tmp/pids
    command: bundle exec puma -C config/puma.rb
    ports:
      - "7001:7001"
