production:
  adapter: postgresql
  encoding: utf-8
  database: <%= ENV['music_backend_db_name'] || 'music_backend_production' %>
  username: <%= ENV['music_backend_db_username'] || 'postgres' %>
  password: <%= ENV['music_backend_db_password'] || '' %>
  host: <%= ENV['db_host'] || 'postgresql' %>
  port: <%= ENV['db_port'] || '5432' %>
  pool: <%= ENV['db_pool'] || 64 %>

development:
  adapter: postgresql
  encoding: utf-8
  database: music_backend-dev
  pool: 64

test: &test
  adapter: postgresql
  encoding: utf-8
  database: music_backend-test
  pool: 64
