production:
  adapter: postgresql
  encoding: utf-8
  database: <%= ENV['db_name'] || 'homeland' %>
  username: <%= ENV['db_username'] || 'postgres' %>
  password: <%= ENV['db_password'] || '' %>
  host: <%= ENV['db_host'] || 'postgresql' %>
  port: <%= ENV['db_port'] || '5432' %>
  pool: <%= ENV['db_pool'] || 64 %>

development:
  adapter: postgresql
  encoding: utf-8
  database: homeland-dev
  pool: 64

test: &test
  adapter: postgresql
  encoding: utf-8
  database: homeland-test
  pool: 64
